# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  askgameshopapi:
    image: askgameshopapi
    build:
      context: .
      dockerfile: AskgAPI/Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
